// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storagedata} from '../models';
import {preferences} from '../models';

export function DtoJsonFirst():Promise<storagedata.PassDto>;

export function LoadedItemsUpdate(arg1:storagedata.LoadedItems):Promise<void>;

export function PreferencesUpdate(arg1:preferences.Preferences):Promise<void>;
