// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DtoJsonFirst() {
  return window['go']['main']['App']['DtoJsonFirst']();
}

export function LoadedItemsUpdate(arg1) {
  return window['go']['main']['App']['LoadedItemsUpdate'](arg1);
}
