// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupSaveFileDialog() {
  return window['go']['main']['App']['BackupSaveFileDialog']();
}

export function DtoJsonFirst() {
  return window['go']['main']['App']['DtoJsonFirst']();
}

export function Exited() {
  return window['go']['main']['App']['Exited']();
}

export function LoadedItemsUpdate(arg1) {
  return window['go']['main']['App']['LoadedItemsUpdate'](arg1);
}

export function OpenBrowserUri(arg1) {
  return window['go']['main']['App']['OpenBrowserUri'](arg1);
}

export function ReloadOpenFileDialog() {
  return window['go']['main']['App']['ReloadOpenFileDialog']();
}
