// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storagedata} from '../models';

export function DtoJsonFirst():Promise<storagedata.PassDto>;

export function GetLockPwdFirst():Promise<string>;
